spring:
  flyway:
    enabled: true

  datasource:
    url: jdbc:mysql://192.168.10.156:3306/subway?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: masterpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

account:
  name: produser
  password: prod